### ISSUE TITLE
[API]建立基础模块接口

### ISSUE THREAD

**Issue by leo220yuyaodog** [leo220yuyaodog/questionnaire#4]
目前我们项目初建，需要先建立问卷、题目、用户等基本的管理API，来为后续复杂业务提供基础的支持。为了降低耦合，我们现阶段先支持基础API，包括基本crud功能。
1. 问卷管理API  包括 get update delete  add 
2. 确定基本的功能。 标准，get-survey 可以返回一个问卷所有题目的data.
效果：
目前前端未完成搭建，测试API，使用postman等API工具，来测试接口实现。

**Comment by szy1840** [comment]
按照这个格式，我们是除了 get-* api 用 GET 请求，其他都是 POST 请求吗

**Comment by leo220yuyaodog** [comment]
> 按照这个格式，我们是除了 get-* api 用 GET 请求，其他都是 POST 请求吗

这里get只表示意思，表示能获得问卷数据。 具体请求类型还需要具体设计。 不过一般来说，其它请求头 类型是POST. 删除操作也有DELETE 。根据实际需要来设计。

**Comment by szy1840** [comment]
哦ok 那我现在先把问卷，问题相关的接口大概设计一下

**Comment by szy1840** [comment]
问卷的CRUD接口已经提交了，暂定为这个接口格式
